# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/leewo/Documents/GitHub/AIX2024/build/07_SIC/07_SIC.srcs/sources_1/ip/dpram_13x256/dpram_13x256.xci
# IP: The module: 'dpram_13x256' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/leewo/Documents/GitHub/AIX2024/build/07_SIC/07_SIC.gen/sources_1/ip/dpram_13x256/dpram_13x256_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dpram_13x256'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/leewo/Documents/GitHub/AIX2024/build/07_SIC/07_SIC.srcs/sources_1/ip/dpram_13x256/dpram_13x256.xci
# IP: The module: 'dpram_13x256' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/leewo/Documents/GitHub/AIX2024/build/07_SIC/07_SIC.gen/sources_1/ip/dpram_13x256/dpram_13x256_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dpram_13x256'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
